# Generated by Django 3.2.3 on 2021-06-06 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chapter1',
            new_name='Chapter',
        ),
    ]
