# Generated by Django 3.2.3 on 2021-06-06 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='lists',
        ),
    ]
