# Generated by Django 3.2.3 on 2021-06-06 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0004_delete_lists'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chapter',
        ),
    ]
